spring:
  data:
    redis:
      host: 146.56.115.136
      database:  0
      port: 6379

  cloud:
    gateway:
        routes:
          - id: google-limit
            filters:
              - name: RequestRateLimiter
                args:
                  key-resolver: "#{@userKeyResolver}"
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 2
                  redis-rate-limiter.requestedTokens: 1
            uri: https://www.google.com
            predicates:
              - Path=/google/**
          - id: naver-limit
            filters:
              - name: RequestRateLimiter
                args:
                  key-resolver: "#{@userKeyResolver}"
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 2
                  redis-rate-limiter.requestedTokens: 1
            uri: http://localost:8082
            predicates:
              - Path=/naver/**